DOPS-420 DOCKERHUB_ORG_NAME var added in ci compose
neonlabsorg/proxy-model.py pull request #198
Opened 2023-11-23 21:54 UTC by vodolaz

2023-11-25 12:42 UTC, afalaleev requested changes

2023-11-25 12:42 UTC, afalaleev commented on docker-compose/docker-compose-ci.yml
> +    image: ${DOCKERHUB_ORG_NAME:-neonlabsorg}/evm_loader:${NEON_EVM_COMMIT}
Please, remove the default value.

2023-11-27 02:43 UTC, vodolaz commented on docker-compose/docker-compose-ci.yml
> +    image: ${DOCKERHUB_ORG_NAME:-neonlabsorg}/evm_loader:${NEON_EVM_COMMIT}
removed

2023-11-27 09:49 UTC, afalaleev approved these changes

2023-11-27 11:31 UTC, merged