NDEV-2811 indexer: Mark Neon EVM transactions as corrupted if Neon logs were truncated
neonlabsorg/proxy-model.py pull request #329
Opened 2024-04-25 10:45 UTC by alfiedotwtf

If we see the string "Log truncated" in the logs, we should mark transactions from that Solana block as corrupted

2024-04-25 13:09 UTC, alfiedotwtf commented
Just a quick question about `proxy/indexer/indexed_objects.py`:

Is `_finalize_log_list()` correct in my change, or should I also iterate over `self._done_neon_tx_list` first to check for ANY corrupted transactions, then if there are:

    - short-circuit here by returning `None`
    - modify `_complete_neon_block()` to skip `add_neon_block(neon_block)`

2024-04-25 21:20 UTC, afalaleev requested changes
> I haven't made any changes yet, but is _finalize_log_list() still correct in my PR...

Yes, it will be nice to refactor `_finalize_log_list()`.
It is critical to see all corrupted txs, not only first in a block

2024-04-25 21:20 UTC, afalaleev commented on proxy/indexer/indexed_objects.py
> +            **src,
You have a problem with restarts in this place.
The actual version doesn't have `is_log_truncated` property in the stored json.
As a result, on restart Indexer will fail if there are some stuck txs.

2024-04-30 17:14 UTC, afalaleev commented on proxy/indexer/indexed_objects.py
> +            **src,
I made a mistake.
Everything is ok, `__init__()` has default value for `is_log_truncated`

2024-04-30 17:14 UTC, afalaleev submitted a review, later dismissed

2024-04-30 17:23 UTC, alfiedotwtf commented
> > I haven't made any changes yet, but is _finalize_log_list() still correct in my PR...
> 
> Yes, it will be nice to refactor `_finalize_log_list()`. It is critical to see all corrupted txs, not only first in a block

Ok, I'll commit my last changes to fix `_finalize_log_list()` now, and wait for approval one last time just in case before merging.

2024-05-14 21:47 UTC, afalaleev requested changes
Reject.
This code doesn't do anything.

2024-05-15 17:03 UTC, alfiedotwtf commented
Maybe I have misunderstood, but just to make sure I've just stepped through it again.

Please see `proxy/indexer/indexed_objects.py : NeonIndexedBlockInfo::_finalize_log_list()`.

Here, `is_log_truncated = any(...)` will detect if there is a single truncated transaction log. If so, we loop through the list and `self._del_neon_tx(tx)` for every transaction. And because `elif tx.is_corrupted()` will return true, we should never reach `tx.complete_event_list()`.

In effect, this PR should now drain `self._neon_tx_dict` and return without adding any events to `neon_tx_res`.

2024-05-21 06:09 UTC, alfiedotwtf commented
Closing as it will be implemented in the new proxy

2024-05-21 06:09 UTC, closed without merging